version: '2'
services:
    sdc-app:
        image: sdc
        external_links:
            - sdc-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/sdc?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    sdc-mysql:
        extends:
            file: mysql.yml
            service: sdc-mysql
